import { FootballPressureResponsePanel } from './FootballPressureResponsePanel';
import { useMemo, useState } from 'react';
import type { CanonicalFootballEvent } from '../../../domain/football/StatsBombContract';
import { orientStatsBombLocation } from '../../../domain/football/StatsBombContract';
import { footballNumericId, observedTeamId, outcomeName, projectControl } from '../../../domain/football/FootballObservation';
import { pressureAnalytics, pressureKind } from '../../../domain/football/FootballPressureAnalytics';
import { analyzeMarkov } from '../../../domain/football/FootballMarkovAnalyzer';
import { estimateXg, estimateXt, attributeChances } from '../../../domain/football/FootballModels';
import { FootballMarkovDiagram } from './FootballMarkovDiagram';
import { FootballPitchPlot } from './FootballPitchPlot';
import './FootballAnalytics.css';

type Tab = 'Mapa' | 'Pressão e resposta' | 'Finalizações' | 'Construção' | 'Markov';
const ratio = (n: number, d: number) => d ? `${(100 * n / d).toFixed(1)}% (${n}/${d})` : 'Sem observações elegíveis';
const decimal = (n: number | undefined) => n === undefined ? 'Indisponível' : n.toFixed(3);
export function FootballAnalyticsPanel({ events, summary = false, teams = [], players = [] }: { readonly events: readonly CanonicalFootballEvent[]; readonly summary?: boolean; readonly teams?: readonly { id: string; name: string }[]; readonly players?: readonly { id: string; number: number; name?: string }[] }) {
  const [tab, setTab] = useState<Tab>('Mapa');
  const [team, setTeam] = useState('');
  const [period, setPeriod] = useState('');
  const [pressure, setPressure] = useState('');
  const [structure, setStructure] = useState('');
  const [block, setBlock] = useState('');
  const [type, setType] = useState('');
  const [markovMode, setMarkovMode] = useState<'zones' | 'actions'>('zones');
  const [mapSource, setMapSource] = useState<'ball' | 'actions'>('ball');
  const [player, setPlayer] = useState('');
  const [mode, setMode] = useState<'actions' | 'trajectories' | 'density'>('density');
  const [pressureMode, setPressureMode] = useState<'volume' | 'incidence' | 'response'>('volume');
  const [selected, setSelected] = useState<string>();
  const filtered = useMemo(() => events.filter(e => (!team || observedTeamId(e) === team || (!observedTeamId(e) && (e.team?.id === Number(team) || teams.findIndex(t => t.id === team) + 1 === e.team?.id))) && (!player || String(e.player?.id ?? (e.scout_trainer.observation?.playerId ? footballNumericId(e.scout_trainer.observation.playerId) : '')) === player) && (!period || e.period === Number(period)) && (!pressure || pressureKind(e) === pressure) && (!structure || e.scout_trainer?.tactical_context?.build_structure === structure) && (!block || e.scout_trainer?.tactical_context?.block === block) && (!type || e.type.id === Number(type))), [events, teams, team, player, period, pressure, structure, block, type]);
  const visible = filtered.filter(e => e.type.id !== 1000);
  const mapEvents = mapSource === 'actions' ? visible : filtered.filter(e => Boolean(e.location ?? e.scout_trainer.observation?.position)).map(e => ({ ...e, location: e.location ?? e.scout_trainer.observation?.position }));
  const control = projectControl(events);
  const shots = visible.filter(e => e.type.id === 16);
  const xg = shots.map(estimateXg), xt = visible.map(e => estimateXt(e)).filter(e => e.eligible);
  const pressureStats = pressureAnalytics(filtered, events);
  const paths = analyzeMarkov(events, new Set(filtered.map(e => e.id)), markovMode);
  const chances = attributeChances(events).filter(c => shots.some(e => e.id === c.shotId));
  const totalTime = Object.values(control.controlledMs).reduce((a, b) => a + b, 0);
  const plotEvents = tab === 'Finalizações' ? shots : tab === 'Pressão e resposta' ? pressureStats.pressed.filter(e => e.location && e.scout_trainer?.observation?.attacksTo).map(e => {
    const direction = e.scout_trainer!.observation!.attacksTo!;
    return { ...e, location: orientStatsBombLocation(e.location!, direction), ...(e.pass?.end_location ? { pass: { ...e.pass, end_location: orientStatsBombLocation(e.pass.end_location, direction) } } : {}), ...(e.carry?.end_location ? { carry: { end_location: orientStatsBombLocation(e.carry.end_location, direction) } } : {}) };
  }) : mapEvents;
  return <section className="football-analytics-panel" aria-label="Leitura futebol">
    <h1>{summary ? 'Resumo do futebol' : 'Análise do futebol'}</h1>
    <div className="football-filters">
      <label>Equipe / equipe pressionada<select value={team} onChange={e => setTeam(e.target.value)}><option value="">Todas</option>{teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      <label>Jogador<select value={player} onChange={e => setPlayer(e.target.value)}><option value="">Todos</option>{[...new Map([...events.filter(e => e.player).map(e => [String(e.player!.id), e.player!.name] as const), ...players.map(p => [String(footballNumericId(p.id)), `#${p.number}${p.name ? ` ${p.name}` : ''}`] as const)]).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
      <label>Período<select value={period} onChange={e => setPeriod(e.target.value)}><option value="">Todos</option><option value="1">1º tempo</option><option value="2">2º tempo</option></select></label>
      <label>Pressão<select value={pressure} onChange={e => setPressure(e.target.value)}><option value="">Todas</option><option value="unknown">Não observada</option><option value="none">Sem pressão</option><option value="individual">Individual</option><option value="collective">Coletiva</option><option value="present_unspecified">Pressão na bola</option></select></label>
      <label>Saída<select value={structure} onChange={e => setStructure(e.target.value)}><option value="">Todas</option>{['2+1','2+2','3+1','3+2','2+3','4+1'].map(s => <option key={s}>{s}</option>)}</select></label>
      <label>Bloco<select value={block} onChange={e => setBlock(e.target.value)}><option value="">Todos</option><option value="high">Alto</option><option value="middle">Médio</option><option value="low">Baixo</option></select></label>
      <label>Ação<select value={type} onChange={e => setType(e.target.value)}><option value="">Todas</option>{[...new Map(events.filter(e => e.type.id !== 1000).map(e => [e.type.id, e.type.name])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    </div>
    <div className="football-metrics"><article><strong>{visible.length}</strong>Ações correspondentes</article><article><strong>{shots.length}</strong>Finalizações · {shots.filter(e => ['Goal', 'Saved'].includes(outcomeName(e) ?? '')).length} no alvo · {shots.filter(e => outcomeName(e) === 'Goal').length} gols</article><article><strong>{decimal(xg.some(e => e.eligible) ? xg.reduce((s, e) => s + (e.value ?? 0), 0) : undefined)}</strong>xG · cobertura {xg.filter(e => e.eligible).length}/{shots.length}</article><article><strong>{decimal(xt.length ? xt.reduce((s, e) => s + (e.value ?? 0), 0) : undefined)}</strong>ΔxT · {xt.length} progressões elegíveis</article></div>
    <p>Posse temporal observada: {totalTime ? teams.map(t => `${t.name} ${ratio(Math.round(control.controlledMs[t.id] ?? 0), totalTime)}`).join(' · ') : 'Cobertura temporal insuficiente'}. {control.segments.length} segmentos registrados; {(control.excludedMs / 1000).toFixed(1)} s observados sem controle.</p>
    {!summary && <nav className="football-analysis-tabs" aria-label="Análises de futebol">{(['Mapa', 'Pressão e resposta', 'Finalizações', 'Construção', 'Markov'] as const).map(t => <button type="button" key={t} aria-pressed={tab === t} onClick={() => { setTab(t); setSelected(undefined); }}>{t}</button>)}</nav>}
    {(!summary && ['Mapa', 'Finalizações', 'Pressão e resposta'].includes(tab)) && <>
      {tab === 'Pressão e resposta' ? <><h2>{teams.find(t => t.id !== team)?.name ?? 'Adversário'} pressionando {teams.find(t => t.id === team)?.name ?? 'equipe com bola'}</h2><p>Ataque da equipe pressionada →. Bola observada, sem tracking de defensores. Incidência {ratio(pressureStats.pressed.length, pressureStats.known.length)}; cobertura {pressureStats.known.length}/{filtered.length}. {pressureStats.episodes.size} episódios identificados. Superação {ratio(pressureStats.episodeData.filter(p => p.outcome === 'beaten').length, pressureStats.episodeData.filter(p => ['beaten', 'not_beaten'].includes(p.outcome)).length)}; {pressureStats.episodeData.filter(p => p.outcome === 'censored').length} censurados; {pressureStats.episodeData.filter(p => p.outcome === 'interrupted').length} interrompidos.</p><div>{([['volume', 'Volume'], ['incidence', 'Incidência'], ['response', 'Resposta']] as const).map(([value, label]) => <button type="button" key={value} aria-pressed={pressureMode === value} onClick={() => setPressureMode(value)}>{label}</button>)}</div><p>Manutenção: {ratio(pressureStats.maintained.length, pressureStats.withControl.length)} · Perda: {ratio(pressureStats.lost.length, pressureStats.withControl.length)}. Finalização posterior: {ratio(pressureStats.reachedShot.length, pressureStats.complete.length)} posses completas; {pressureStats.possessions.length - pressureStats.complete.length} incompletas.</p></> : <div>{([['actions', 'Ações'], ['trajectories', 'Trajetórias'], ['density', 'Mapa de calor']] as const).map(([value, label]) => <button type="button" key={value} aria-pressed={mode === value} onClick={() => setMode(value)}>{label}</button>)}</div>}
      {tab === 'Mapa' && <div className="football-analysis-tabs" aria-label="Dados do mapa"><button type="button" aria-pressed={mapSource === 'ball'} onClick={() => setMapSource('ball')}>Bola observada</button><button type="button" aria-pressed={mapSource === 'actions'} onClick={() => setMapSource('actions')}>Somente ações</button></div>}
      <FootballPitchPlot events={plotEvents} mode={tab === 'Pressão e resposta' ? pressureMode === 'response' ? 'trajectories' : 'density' : mode} onSelect={setSelected} cells={tab === 'Pressão e resposta' && pressureMode !== 'response' ? pressureStats.zones.map(z => ({ index: z.index, value: pressureMode === 'volume' ? z.pressed : z.known ? z.pressed / z.known * 100 : 0, label: `Zona ${z.index}: ${z.pressed}/${z.known} sob pressão; cobertura ${z.known}/${z.total}` })) : undefined} />
      <p>{plotEvents.filter(e => e.location).length}/{plotEvents.length} com posição. {tab === 'Pressão e resposta' ? `${pressureStats.spatialExcluded} excluídos por posição/orientação ausente.` : mode === 'density' ? 'Mapa de calor: contagem de posições registradas por célula 10×10; não representa tempo de permanência. Coordenadas originais do campo.' : 'Trajetórias ligam somente origem e destino da mesma ação.'}</p>
    </>}
    {!summary && tab === 'Pressão e resposta' && <FootballPressureResponsePanel events={visible} history={events} onSelect={setSelected} />}
    {!summary && tab === 'Markov' && <><h2>Diagramas de Markov</h2><div className="football-analysis-tabs"><button type="button" aria-pressed={markovMode === 'zones'} onClick={() => setMarkovMode('zones')}>Entre zonas</button><button type="button" aria-pressed={markovMode === 'actions'} onClick={() => setMarkovMode('actions')}>Entre ações</button></div><p>Probabilidade da próxima transição observada, condicionada ao estado de origem. Setas mostram direção, percentual e contagem; não são previsões.</p>{markovMode === 'zones' && <p>Zonas orientadas na direção do ataque. Registros sem posição ou direção conhecida não definem uma zona.</p>}<FootballMarkovDiagram paths={paths} onSelect={setSelected} /><table><thead><tr><th>De → para</th><th>Próxima transição</th><th>Evidências</th></tr></thead><tbody>{paths.matrix.filter(c => c.count).map(c => <tr key={`${c.from}-${c.to}`}><td>{c.from} → {c.to}</td><td>{ratio(c.count, c.total)}</td><td><button type="button" onClick={() => setSelected(c.evidence[0]?.eventIds[0])}>{c.count} transições</button></td></tr>)}</tbody></table><h2>Finalização por saída observada</h2><p>Denominador: posses distintas completas que contêm eventos correspondentes. Associação observada.</p><table><thead><tr><th>Saída</th><th>Finalização</th><th>Incompletas</th><th>Posses</th></tr></thead><tbody>{paths.cohorts.map(c => <tr key={c.structure}><td>{c.structure}</td><td>{ratio(c.numerator, c.denominator)}</td><td>{c.incomplete}</td><td>{c.evidence.map(p => <button type="button" key={p.id} onClick={() => setSelected(p.events[0]?.id)}>{p.id}</button>)}</td></tr>)}</tbody></table>{paths.cohorts[0].denominator > 0 && paths.cohorts[1].denominator > 0 && <p>3+1 versus 3+2: {(100 * (paths.cohorts[0].numerator / paths.cohorts[0].denominator - paths.cohorts[1].numerator / paths.cohorts[1].denominator)).toFixed(1)} p.p.</p>}</>}
    {!summary && tab === 'Construção' && <><h2>Progressões e ameaça</h2><p>ΔxT = valor de destino − valor de origem, incluindo valores negativos. Passe completo e condução com controle mantido.</p><table><thead><tr><th>Evento</th><th>Origem</th><th>Destino</th><th>ΔxT</th></tr></thead><tbody>{xt.map(x => <tr key={x.eventId}><td><button onClick={() => setSelected(x.eventId)}>{events.find(e => e.id === x.eventId)?.type.name}</button></td><td>{decimal(x.start)}</td><td>{decimal(x.end)}</td><td>{decimal(x.value)}</td></tr>)}</tbody></table><h2>Por posse</h2><table><thead><tr><th>Posse</th><th>Soma xG</th><th>Soma ΔxT</th><th>xT final</th></tr></thead><tbody>{control.segments.map(p => { const gains = p.events.map(e => estimateXt(e)).filter(e => e.eligible); const shotValues = p.events.map(estimateXg).filter(e => e.eligible); return <tr key={p.id}><td>{p.id}</td><td>{decimal(shotValues.length ? shotValues.reduce((s,e) => s + (e.value ?? 0),0) : undefined)}</td><td>{decimal(gains.length ? gains.reduce((s,e) => s + (e.value ?? 0),0) : undefined)}</td><td>{decimal(gains.at(-1)?.end)}</td></tr>; })}</tbody></table></>}
    {!summary && tab === 'Finalizações' && <><h2>xG após a última ação criadora</h2><ul>{chances.map(c => <li key={c.shotId}>{decimal(c.estimate.value)} · {c.creatorId ? `Ação ${events.find(e => e.id === c.creatorId)?.index}` : 'Sem ação criadora identificada'} · {c.estimate.source}/{c.estimate.modelVersion}</li>)}</ul></>}
    {selected && <aside role="status"><button type="button" onClick={() => setSelected(undefined)}>Fechar detalhe</button>{(() => { const event = events.find(e => e.id === selected); const possession = control.segments.find(p => p.events.some(e => e.id === selected) || p.marks.some(m => m.eventId === selected)); return <><h2>{event?.timestamp.slice(3)} · {event?.team?.name} · {event?.type.name}</h2><p>{event?.player?.name ?? 'Atleta não identificado'} · {event ? outcomeName(event) : ''} · Pressão: {event ? pressureKind(event) : '?'}</p><p>Posição: {event?.location?.join(', ') ?? 'Não observada'} · Saída: {event?.scout_trainer?.tactical_context?.build_structure ?? 'Não observada'}</p><h3>Sequência da posse {possession?.id ?? 'não identificada'}</h3><ol>{possession?.events.map(e => <li key={e.id}>{e.timestamp.slice(3,8)} · {e.type.name} · {outcomeName(e)}</li>)}</ol></>; })()}</aside>}
    <details><summary>Eventos correspondentes e cobertura</summary><table><thead><tr><th>Tempo</th><th>Equipe / atleta</th><th>Ação</th><th>Resultado</th><th>Pressão</th></tr></thead><tbody>{visible.map(e => <tr key={e.id}><td><button type="button" onClick={() => setSelected(e.id)}>{e.timestamp.slice(3)}</button></td><td>{e.team?.name} / {e.player?.name ?? '?'}</td><td>{e.type.name}</td><td>{outcomeName(e)}</td><td>{pressureKind(e)}</td></tr>)}</tbody></table></details>
    <p className="football-model-note">Modelos locais v1 · dados de treino: <a href="https://github.com/hudl/open-data">StatsBomb Open Data</a>, Copa masculina 2022. xG distância/ângulo; xT 12×8. Validade fora desse corpus não demonstrada. Valores importados mantêm fonte distinta.</p>
  </section>;
}
