import type { CanonicalFootballEvent } from '../../../domain/football/StatsBombContract';
import { pressureAnalytics } from '../../../domain/football/FootballPressureAnalytics';
import { estimateXg, estimateXt } from '../../../domain/football/FootballModels';

export function FootballPressureResponsePanel({ events, history, onSelect }: { readonly events: readonly CanonicalFootballEvent[]; readonly history: readonly CanonicalFootballEvent[]; readonly onSelect: (id: string) => void }) {
  const stats = pressureAnalytics(events, history);
  const methods = [...new Set(stats.pressed.map(e => e.type.name))];
  return <section><h2>Como responderam à pressão?</h2><p>Controle imediato usa somente ações com controle posterior conhecido. Disputa e parada permanecem categorias separadas.</p><table><thead><tr><th>Método</th><th>Ações</th><th>Manutenção / conhecidas</th><th>Perda / conhecidas</th><th>Disputa</th><th>Superação observada</th><th>ΔxT</th></tr></thead><tbody>{methods.map(method => {
    const subset = stats.pressed.filter(e => e.type.name === method);
    const result = pressureAnalytics(subset, history);
    const gains = subset.map(e => estimateXt(e)).filter(e => e.eligible);
    return <tr key={method}><td>{method}</td><td><button type="button" onClick={() => onSelect(subset[0].id)}>{subset.length}</button></td><td>{result.maintained.length}/{result.withControl.length}</td><td>{result.lost.length}/{result.withControl.length}</td><td>{subset.filter(e => e.scout_trainer?.observation?.after?.kind === 'contested').length}</td><td>{subset.filter(e => e.scout_trainer?.observation?.pressureBeaten === 'yes').length}/{subset.filter(e => ['yes','no'].includes(e.scout_trainer?.observation?.pressureBeaten ?? '')).length} ações</td><td>{gains.length ? gains.reduce((sum,e) => sum + (e.value ?? 0),0).toFixed(3) : 'Indisponível'}</td></tr>;
  })}</tbody></table><h3>Episódios e caminhos observados</h3>{stats.episodeData.map(p => <details key={`${p.id}-${p.start.id}`}><summary>{p.start.timestamp.slice(3,8)} · {p.events.length} ações · {({beaten:'superada',not_beaten:'não superada',interrupted:'interrompida',censored:'resultado não observado'})[p.outcome]}</summary><ol>{p.events.map(e => <li key={e.id}><button type="button" onClick={() => onSelect(e.id)}>{e.timestamp.slice(3,8)} · {e.type.name}</button> · {e.scout_trainer?.observation?.lineBreak && e.scout_trainer.observation.lineBreak !== 'unknown' ? 'Quebra de linha observada' : 'Quebra de linha não observada'} · recepção {e.scout_trainer?.observation?.reception ?? 'não observada'}</li>)}</ol></details>)}<p>xG nas posses expostas: {(() => { const values = [...new Map(stats.possessions.flatMap(p => p.events).filter(e => e.type.id === 16).map(e => [e.id,estimateXg(e)])).values()].filter(e => e.eligible); return values.length ? `${values.reduce((sum,e) => sum+(e.value ?? 0),0).toFixed(3)} (${values.length} chutes únicos)` : 'Indisponível'; })()}. Cada chute entra uma única vez na coorte.</p></section>;
}
