import { expect, test } from '@playwright/test';

test('single recorder saves pressure, player and pass, then displays heatmap and Markov', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 900 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Nova partida' }).last().click();
  await page.getByLabel('Modalidade').selectOption('football');
  await page.getByRole('button', { name: 'Adicionar atleta', exact: true }).first().click();
  await page.getByLabel('Camisa Equipe A 1', { exact: true }).fill('7');
  await page.getByLabel('Nome Equipe A 1', { exact: true }).fill('Jogador de teste');
  await page.getByRole('button', { name: 'Iniciar partida' }).click();
  await expect(page.getByRole('button', { name: 'Modo detalhado', exact: true })).toHaveCount(0);
  await expect(page.getByLabel('Jogador da ação')).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar relógio', exact: true }).click();
  const controls = page.getByLabel('Controle observado');
  await controls.getByRole('button').first().click();
  await expect(page.getByRole('button', { name: 'Passe certo A', exact: true })).toBeEnabled();
  await page.keyboard.press('p');
  await expect(page.getByText('Pressão na bola registrada.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Pressão na bola P', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByText('Ajustes da partida', { exact: true }).click();
  await page.getByLabel(/Direção de ataque de/).first().selectOption('x120');
  await page.getByText('Ajustes da partida', { exact: true }).click();
  const players = page.getByLabel('Jogador da ação');
  await players.selectOption({ label: '#7 Jogador de teste' });
  await page.getByRole('button', { name: 'Passe certo A', exact: true }).click();
  const field = page.getByRole('application');
  const box = await field.boundingBox();
  if (!box) throw new Error('Campo não encontrado');
  await field.click({ position: { x: box.width * .15, y: box.height * .5 } });
  await field.click({ position: { x: box.width * .5, y: box.height * .5 } });
  await expect(page.getByRole('button', { name: 'Registrar ação', exact: true })).toHaveCount(0);
  await expect(page.getByText('Ação registrada.')).toBeVisible();
  await page.keyboard.press('s');
  await expect(page.getByText('Sem pressão registrada.')).toBeVisible();
  await field.click({ position: { x: box.width * .9, y: box.height * .5 } });
  await expect(page.getByText('Marco salvo.')).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'output/football-simple-recording.png', fullPage: true });
  await page.getByRole('button', { name: 'Análise', exact: true }).click();
  await expect(page.getByRole('img', { name: 'Mapa de calor do campo de futebol' })).toBeVisible();
  await expect(page.getByText('Sem posições elegíveis para este mapa de calor.')).toHaveCount(0);
  await page.screenshot({ path: 'output/football-simple-heatmap.png', fullPage: true });
  await page.getByRole('combobox', { name: 'Jogador', exact: true }).selectOption({ label: '#7 Jogador de teste' });
  await expect(page.getByText('Sem posições elegíveis para este mapa de calor.')).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Jogador', exact: true }).selectOption('');
  await page.getByRole('button', { name: 'Markov', exact: true }).click();
  await expect(page.getByRole('img', { name: 'Diagrama de Markov com probabilidades e contagens' })).toBeVisible();
  await page.screenshot({ path: 'output/football-simple-markov.png', fullPage: true });
  await page.getByRole('button', { name: 'Registro', exact: true }).click();
  await page.reload();
  const resume = page.getByRole('button', { name: 'Continuar registro' });
  await expect(page.getByRole('application').or(resume)).toBeVisible();
  if (await resume.isVisible().catch(() => false)) await resume.click();
  await expect(page.getByRole('application')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Modo detalhado', exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.screenshot({ path: 'output/football-simple-mobile.png', fullPage: true });
});
