import type { TrainingProfile } from '../types';

const primarySkills = Object.freeze(['serve', 'reception', 'attack', 'block'] as const);
const completeSkills = Object.freeze([
  'serve',
  'reception',
  'set',
  'attack',
  'block',
  'dig',
  'free_ball',
] as const);

export const defaultTrainingProfiles = Object.freeze([
  {
    kind: 'training',
    id: 'training_basic_v1',
    version: '1.0.0',
    name: 'Básico',
    complexityProfileId: 'basic',
    enabledSkills: primarySkills,
    targetAccuracy: 0.8,
    targetAverageTimeMs: 4000,
    exerciseCount: 10,
  },
  {
    kind: 'training',
    id: 'training_operational_v1',
    version: '1.0.0',
    name: 'Operacional',
    complexityProfileId: 'operational',
    enabledSkills: primarySkills,
    targetAccuracy: 0.85,
    targetAverageTimeMs: 3500,
    exerciseCount: 10,
  },
  {
    kind: 'training',
    id: 'training_tactical_v1',
    version: '1.0.0',
    name: 'Tático',
    complexityProfileId: 'tactical',
    enabledSkills: completeSkills,
    targetAccuracy: 0.88,
    targetAverageTimeMs: 3200,
    exerciseCount: 10,
  },
  {
    kind: 'training',
    id: 'training_advanced_v1',
    version: '1.0.0',
    name: 'Avançado',
    complexityProfileId: 'advanced',
    enabledSkills: completeSkills,
    targetAccuracy: 0.9,
    targetAverageTimeMs: 3000,
    exerciseCount: 12,
  },
  {
    kind: 'training',
    id: 'training_cbv_2025_26',
    version: '1.0.0',
    name: 'CBV 2025/26',
    complexityProfileId: 'tactical',
    competitionProfileId: 'cbv_superliga_reference_2025_26',
    enabledSkills: completeSkills,
    targetAccuracy: 0.9,
    targetAverageTimeMs: 3000,
    exerciseCount: 12,
  },
  {
    kind: 'training',
    id: 'training_custom_v1',
    version: '1.0.0',
    name: 'Personalizado',
    complexityProfileId: 'basic',
    enabledSkills: completeSkills,
    exerciseCount: 15,
  },
] satisfies readonly TrainingProfile[]);
